# AI Generated: GitHub Copilot - 2025-08-16
# Cloudflare Worker configuration for scheduled TMDB updates
name = "boxdbuddy-scheduler"
main = "functions/scheduled/tmdb-daily-update/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "MOVIES_DB"
database_name = "boxdbuddy-movies"
database_id = "466c5909-8a9a-418c-927b-2d36c118e270"

# Daily TMDB sync job - runs at 2 AM UTC daily
[triggers]
crons = ["0 2 * * *"]

[vars]
TMDB_API_KEY = ""  # Set this via: wrangler secret put TMDB_API_KEY