# AI Generated: GitHub Copilot - 2025-08-17
name = "boxdbuddy"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Override dashboard build configuration for web-only deployment
[build]
command = "npm install && npm run build"
cwd = "."

[[d1_databases]]
binding = "MOVIES_DB"
database_name = "boxdbuddy-movies"
database_id = "466c5909-8a9a-418c-927b-2d36c118e270"

[[kv_namespaces]]
binding = "MOVIES_KV"
id = "40b6505549fe45289fb872db9df32546"
