# AI Generated: GitHub Copilot - 2025-08-17
name = "boxdbud"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Note: Build commands must be configured in Cloudflare Pages dashboard
# Cloudflare Pages does not support [build] section in wrangler.toml
# Dashboard should be set to:
# - Build command: npm install && npm run build
# - Build output directory: dist
# - Root directory: / (or blank)

[[d1_databases]]
binding = "MOVIES_DB"
database_name = "boxdbuddy-movies"
database_id = "466c5909-8a9a-418c-927b-2d36c118e270"

[[kv_namespaces]]
binding = "MOVIES_KV"
id = "40b6505549fe45289fb872db9df32546"
