name = "boxdbuddies-web"
main = "web/worker/src/index.ts"
compatibility_date = "2024-01-15"

[env.production]
vars = { ENVIRONMENT = "production" }

[pages]
# Helps Pages detect build output when used; ignored by Workers deploys.
pages_build_output_dir = "web/frontend/dist"

# Cloudflare Pages configuration notes
# Framework preset: None
# Build command: cd web/frontend && npm install && npm run build
# Build output directory: web/frontend/dist
# Root directory: (leave blank)
# Environment variables for production:
# NODE_ENV = production
