name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for all platforms
      run: |
        npm run tauri build -- --target x86_64-pc-windows-msvc
        npm run tauri build -- --target x86_64-apple-darwin
        npm run tauri build -- --target x86_64-unknown-linux-gnu
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/*/release/bundle/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update package version
      run: |
        npm version ${{ github.ref_name }} --no-git-tag-version
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        git commit -m "chore: bump version to ${{ github.ref_name }}" || exit 0
