name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.1)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write
  actions: read

jobs:
  # Build for Windows
  build-windows:
    runs-on: windows-latest
    env:
      # AI Generated: GitHub Copilot - 2025-08-08 (enable sccache for faster Rust builds)
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      CARGO_INCREMENTAL: 0
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install sccache (Windows)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: cargo install sccache
        env:
          RUSTC_WRAPPER: ""

      - name: Cache sccache (Windows)
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\Mozilla\sccache
          key: windows-sccache-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            windows-sccache-

      - name: Install dependencies
        run: npm ci

      - name: Install WiX Toolset (Windows)
        shell: powershell
        run: |
          # AI Generated: GitHub Copilot - 2025-08-08
          choco install wixtoolset --no-progress -y
          if (Test-Path Env:WIX) {
            "$env:WIX\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } else {
            $wixBin = (Get-ChildItem -Path "C:\\Program Files (x86)\\WiX Toolset*" -Directory |
              Sort-Object Name -Descending | Select-Object -First 1).FullName + "\\bin"
            if (Test-Path $wixBin) { $wixBin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append }
          }
          where.exe candle
          where.exe light

      - name: Verify icons and configs
        run: |
          echo Listing icons and config files...
          dir src-tauri\icons
          dir src-tauri
          type src-tauri\tauri.conf.json
          type src-tauri\tauri.windows.conf.json

      - name: Cache cargo (Windows)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: windows-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            windows-cargo-

      - name: Build Windows MSI
        # AI Generated: GitHub Copilot - 2025-08-07
        # Use Windows path separators per PR review suggestion
        run: npm run tauri build -- -c src-tauri\\tauri.windows.conf.json --bundles msi

      - name: sccache stats (Windows)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: sccache --show-stats || echo "sccache not available"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: src-tauri/target/release/bundle/msi/*.msi

  # Build for macOS
  build-macos:
    runs-on: macos-latest
    env:
      # AI Generated: GitHub Copilot - 2025-08-08 (enable sccache for faster Rust builds)
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      CARGO_INCREMENTAL: 0
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install sccache (macOS)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: cargo install sccache
        env:
          RUSTC_WRAPPER: ""

      # AI Generated: GitHub Copilot - 2025-08-07 (relocate cache per review feedback before build)
      - name: Cache cargo (macOS)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: macos-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            macos-cargo-

      - name: Cache sccache (macOS)
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Mozilla.sccache
          key: macos-sccache-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            macos-sccache-

      - name: Install dependencies
        run: npm ci

      - name: Build macOS DMG
        run: npm run tauri build -- --bundles dmg

      - name: sccache stats (macOS)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: sccache --show-stats || echo "sccache not available"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg

  # Build for Linux
  build-linux:
    runs-on: ubuntu-latest
    env:
      # AI Generated: GitHub Copilot - 2025-08-08 (enable sccache for faster Rust builds)
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
      CARGO_INCREMENTAL: 0
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install sccache (Linux)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: cargo install sccache
        env:
          RUSTC_WRAPPER: ""

      # AI Generated: GitHub Copilot - 2025-08-07 (relocate cache prior to build for consistency)
      - name: Cache cargo (Linux)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: linux-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            linux-cargo-

      - name: Cache sccache (Linux)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/sccache
          key: linux-sccache-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            linux-sccache-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup2.4-dev \
            libsoup-3.0-dev

      - name: Create Ubuntu 24.04 compatibility symlinks
        run: |
          # Create pkg-config compatibility symlinks for Ubuntu 24.04 naming (4.1 -> 4.0)
          ARCH_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig"
          for pc in webkit2gtk javascriptcoregtk; do
            if [ -f "${ARCH_PATH}/${pc}-4.1.pc" ] && [ ! -f "${ARCH_PATH}/${pc}-4.0.pc" ]; then
              sudo ln -sf "${ARCH_PATH}/${pc}-4.1.pc" "${ARCH_PATH}/${pc}-4.0.pc"
            fi
          done
          # Create library compatibility symlinks (handle .so and .so.0 targets)
          LIB_PATH="/usr/lib/x86_64-linux-gnu"
          for lib in webkit2gtk javascriptcoregtk; do
            if [ ! -f "${LIB_PATH}/lib${lib}-4.0.so" ]; then
              if [ -f "${LIB_PATH}/lib${lib}-4.1.so" ]; then
                sudo ln -sf "${LIB_PATH}/lib${lib}-4.1.so" "${LIB_PATH}/lib${lib}-4.0.so"
              elif [ -f "${LIB_PATH}/lib${lib}-4.1.so.0" ]; then
                sudo ln -sf "${LIB_PATH}/lib${lib}-4.1.so.0" "${LIB_PATH}/lib${lib}-4.0.so"
              fi
            fi
          done
          # Set PKG_CONFIG_PATH for build compatibility
          echo "PKG_CONFIG_PATH=${ARCH_PATH}:${PKG_CONFIG_PATH:-}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build Linux packages
        run: |
          echo "Building Linux bundles (deb, appimage)"
          # AI Generated: GitHub Copilot - 2025-08-07 (combined bundles build for reliability)
          npm run tauri build -- --bundles deb,appimage
          echo "Listing produced bundle files for diagnostics:" 
          find src-tauri/target/release/bundle -maxdepth 4 -type f -printf "%p\n" || true

      - name: sccache stats (Linux)
        # AI Generated: GitHub Copilot - 2025-08-08
        run: sccache --show-stats || echo "sccache not available"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: warn

  # Create GitHub Release
  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate checksums
        run: |
          set -e
          VERSION="${{ github.event.inputs.version || github.ref_name }}"
          echo "Generating SHA256 checksums for release artifacts (version: $VERSION)"
          echo "# BoxdBuddies Artifact Checksums ($VERSION)" > CHECKSUMS.txt
          echo "Generated on $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> CHECKSUMS.txt
          echo "" >> CHECKSUMS.txt
          shopt -s nullglob
          missing=0
          found=0
          missing_patterns=()
          # Expand patterns and hash all matching files (handles 0, 1, or many files per pattern)
          patterns=(
            windows-msi/*.msi
            macos-dmg/*.dmg
            linux-packages/*.deb
            linux-packages/*.AppImage
          )
          for pattern in "${patterns[@]}"; do
            matches=( $pattern )
            if ((${#matches[@]})); then
              for file in "${matches[@]}"; do
                sha256sum "$file" >> CHECKSUMS.txt
                found=$((found+1))
              done
            else
              echo "Skipping missing artifact(s): $pattern" >&2
              missing=$((missing+1))
              missing_patterns+=("$pattern")
            fi
          done
          echo "" >> CHECKSUMS.txt
          echo "Integrity: Verify with: sha256sum -c CHECKSUMS.txt (ignore header lines)." >> CHECKSUMS.txt
          echo "Missing artifacts skipped: $missing" >> CHECKSUMS.txt
          echo "Artifacts hashed: $found" >> CHECKSUMS.txt
          echo "Done generating checksums (found=$found, missing=$missing)."
          if [ "$missing" -gt 0 ]; then
            echo "ERROR: One or more expected artifacts are missing ($missing):" >&2
            for p in "${missing_patterns[@]}"; do
              echo " - $p" >&2
            done
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          files: |
            windows-msi/*.msi
            macos-dmg/*.dmg
            linux-packages/*.deb
            linux-packages/*.AppImage
            CHECKSUMS.txt
          generate_release_notes: true
          draft: false
          prerelease: false
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
